services:
  db:
    container_name: postgres_container
    image: postgres:14.17
    ports:
      - 5000:5432
    environment:
      POSTGRES_DB: db 
      POSTGRES_USER: db_user 
      POSTGRES_PASSWORD: db_password 
    volumes:
      - ./postgres/data:/var/lib/postgresql/data 



  af:
    container_name: airflow_container
    image: apache/airflow:3.0.0
    ports:
      - 8000:8080
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN:

